source "https://rubygems.org"
 
 gem "cucumber"
 gem "capybara"
 gem "selenium-webdriver"
 gem "gherkin"
 gem "rescue"
 gem "rspec"
 gem "httparty"
 gem "rake"
 gem "rails"
 gem "cucumber-rails"
 gem "database_cleaner"
 gem "bundler"